### ISSUE TITLE
Why are fields not private?

### ISSUE THREAD

**Issue by marceloverdijk** [javserlah/qforce#4]
Is there a reason that fields of the model classes like

https://github.com/javserlah/qforce/blob/4f75e51011e43ba3d84e3c04ad4fe240e200952d/src/main/java/nl/qnh/qforce/domain/MovieModel.java#L12

are not private?

**Comment by javserlah** [comment]
No, just a mistake from my side when trying to be quick. They should totally be private as there is no need for them to be seen from outside the scope of the class.

**Comment by marceloverdijk** [comment]
OK.
