### ISSUE TITLE
What code style rules are used?

### ISSUE THREAD

**Issue by marceloverdijk** [javserlah/qforce#6]
Did you use any code style rules?

E.g. we see:

https://github.com/javserlah/qforce/blob/4f75e51011e43ba3d84e3c04ad4fe240e200952d/src/main/java/nl/qnh/qforce/controller/QForceController.java#L45

`return person.isPresent()?ResponseEntity.ok().body(person.get()):new ResponseEntity<>(HttpStatus.NOT_FOUND);`

as one liner without any spaces is very difficult to read.

**Comment by javserlah** [comment]
Yes, i always try to be clean when writing code because is really important to understand the code if someone else reads it afterwards. In this case I just tried to make a quick response just for returning both status.

**Comment by marceloverdijk** [comment]
OK.
